server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:  #在此处配置需要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于bindings整合
          type: rabbit #消息组件的类型
      bindings: #服务的整合管理
        output1: #这个名字是一个通道的名称
          destination: studyExchange #rabbitmq中的exchange名称
          content-type: application/json #设置消息的类型为json  也可以是文本text/plain
          binder: defaultRabbit #设置要绑定的消息服务的名称


eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/

