server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动+1 依次往后
        port: 8719

  management:
    endpoints:
      web:
        exposure:
          include: '*'


service-url:
  nacos-user-service: http://nacos-payment-provider