server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路由地址和这个相匹配后进行路由
#            - After=2022-01-04T14:58:36.941+08:00[Asia/Shanghai] #在此时间之后才能访问（before between类比此参数）
#            - Cookie=username,wangyue
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id 并且值为整数  curl http://127.0.0.1:9527/payment/get/2 --cookie "username=wangyue" -H "X-Request-Id:123"
#            - Host=**.baidu.com # "Host: news.baidu.com"
#            - Method=GET #GET POST ...
#            - Query=username, \d+ #要有参数名username并且值为整数才能路由

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/create/**
          filters:
            - AddRequestParameter=username,wangyue

eureka:
  instance:
    hostname: cloud-gate-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7003.com:7003/eureka