server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: http://localhost:8001
          predicates:
            - Path=/payment/hystrix/timeout/**

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/hystrix/ok/**

eureka:
  instance:
    hostname: cloud-gate-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7003.com:7003/eureka