server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discorvey:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

