server:
  port: 8001
spring:
  application:
    name: cloud-payment-service

#eureka:
#  client:
#   #表示是否向注册中心注册自己 默认为true
#    register-with-eureka: true
#   #表示是否从Eureka抓取已有的注册信息，默认为true。单节点无所谓，集群节点必须设置为true才能配合rabbion使用负载均衡
#    fetch-registry: true
#    service-url:
#    #设置与eurekaServer交互的地址 查询服务和注册服务都依赖这个地址
#      defalutZone: http://localhost:7001/eureka/

eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #EurekaClient向服务端发送心跳的时间间隔，单位秒  默认30秒
    lease-renewal-interval-in-seconds: 2
    #Eureka服务端在收到最后一次心跳后等待的时间上限，超时剔除服务
    lease-expiration-duration-in-seconds: 10



